apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: {{ artifact-id }}
  labels:
    p6m.dev/app: {{ artifact-id }}
spec:
  config:{% if service-protocol == 'gRPC' %}
    GRPC_PORT: "8080"  # Service Port
    SERVER_PORT: "8081" # Management Port{% elif service-protocol == 'GraphQL' %}
    SERVER_PORT: "8080" # Service Port
    MANAGEMENT_SERVER_PORT: "8081" # Management Port{% endif %}
    LOGGING_STRUCTURED: "true"{% if persistence == 'CockroachDB' %}{% if project-language == '.NET' %}
    ConnectionStrings__CockroachDBConnection: "Host=$(crdb_{{ artifact_id }}_db_endpoint);Port=$(crdb_{{ artifact_id }}_db_port);Database={{ artifact_id }}_db;Username=$(crdb_{{ artifact_id }}_db_username);Password=$(crdb_{{ artifact_id }}_db_password);sslmode=require"{% else %}
    PERSISTENCE_DATABASE_URL: "$(crdb_{{ artifact_id }}_jdbc_connection_string)" {% endif %}{% endif %}
  resources: {% if persistence == 'CockroachDB' %}
    crdb:
      - name: {{ artifact-id }}{% else %}{}{% endif %}
  deployment:
    image: {{ artifact-id }}-server:latest
    ports:
      - protocol: {% if service-protocol == 'gRPC' %}grpc{% else %}http{% endif %}
        port: 8080
      - protocol: http
        port: 8081
    readinessProbe:
      port: 8081
      path: /health/readiness
